--Create second availability group on second failover cluster with replicas and listener
--Run this on the primary replica of the secondary Availability Group
:CONNECT WINSRV03\INSTA1
CREATE AVAILABILITY GROUP [AG_DC2] 
FOR  
REPLICA ON
N'WINSRV03\INSTA1' WITH
(
   ENDPOINT_URL = N'TCP://WINSRV03.ADAM.LOCAL:5022',  
   FAILOVER_MODE = AUTOMATIC,  
   AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,  
   SECONDARY_ROLE(ALLOW_CONNECTIONS = NO),  
   SEEDING_MODE = AUTOMATIC
),  
N'WINSRV04\INSTA1' WITH
(  ENDPOINT_URL = N'TCP://WINSRV04.ADAM.LOCAL:5022',  
   FAILOVER_MODE = AUTOMATIC,  
   AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,  
   SECONDARY_ROLE(ALLOW_CONNECTIONS = NO),  
   SEEDING_MODE = AUTOMATIC
)
LISTENER 'AG_DC2_LISTENER'
(
   WITH IP ( ('192.168.0.202','255.255.255.0')
   PORT = 1433
);  
GO  
   