CREATE AVAILABILITY GROUP [DBADistributedAG]  
  WITH (DISTRIBUTED)  
  AVAILABILITY GROUP ON  
  'AG_DC1' WITH   
  (  
    LISTENER_URL = 'tcp://dbadaglistener1.ADAM.LOCAL:5022',   
     AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,  
     FAILOVER_MODE = MANUAL,  
     SEEDING_MODE = AUTOMATIC
   ),  
  'AG_DC2' WITH   
    (  
     LISTENER_URL = 'tcp://dbadaglistener2.ADAM.LOCAL:5022',  
     AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,  
     FAILOVER_MODE = MANUAL,  
     SEEDING_MODE = AUTOMATIC
   );